<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('products')->truncate();
        DB::table('products')->insert([
            [
                'title' => 'Bichon Frise Puppies For Adoption',
                'description' => 'The Bichon Frise is a small, sturdy dog. When the dog is clipped in a show cut the body gives off a round appearance. The skull is slightly rounded.',
                'images' => 'https://kenh14cdn.com/2016/c16-1469688809484.jpg',
                'categoryId' => '1',
                'price' => 180,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Boo Puppies For Adoption',
                'description' => 'The Chow Chow is a true masterpiece of dignity and beauty. They possess the unique characteristic of having a blue-black tongue. They are keenly intelligent, have an independent spirit, and display a dignified demeanor.',
                'images' => 'https://kenh14cdn.com/2016/c11-1469688809458.jpg',
                'categoryId' => '1',
                'price' => 185,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'King Charles Spaniel Puppies For Adoption',
                'description' => 'King Charles Spaniel has a large muzzle, large eyes, and long, highly set ears.',
                'images' => 'https://kenh14cdn.com/2016/c6-1469688809426.jpg',
                'categoryId' => '1',
                'price' => 200,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Lhasa Apso Puppies For Adoption',
                'description' => 'They have long and silky fur with miniature size. Eyes and nose are distinctively black. They have punch face.',
                'images' => 'https://baomoi-photo-1-td.zadn.vn/w700_r1/18/01/10/139/24577236/6_153481.jpg',
                'categoryId' => '1',
                'price' => 177,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Maltese Puppies For Adoption',
                'description' => 'The Maltese exudes great joy and delight. They are highly intelligent, animated, and playful. They are very social.',
                'images' => 'https://baomoi-photo-1-td.zadn.vn/w700_r1/15/09/26/139/17593519/14.jpg',
                'categoryId' => '1',
                'price' => 220,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Minpin Puppies For Adoption',
                'description' => 'The Minpin is a small, compact, square dog. The head is in proportion to the body. The skull appears flat, tapering forward toward the muzzle.',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2015/07/minpin-puppy-300x168.jpg',
                'categoryId' => '1',
                'price' => 167,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Collie Puppies For Adoption',
                'description' => 'The Collie is a large, lean, strong dog. The top of the skull is flat and the eyebrows are arched.',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2015/07/Collie-Puppies-1-300x230.jpg',
                'categoryId' => '1',
                'price' => 267,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'French Bull Dog Puppies For Adoption',
                'description' => 'The Bulldog is moderate in size, heavy, and built low to the ground. They are strong, kind, amiable, and courageous. This breed is not vicious or aggressive and is quite dignified. They possess a passive demeanor and have a quirky sense of humor.',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2013/10/french-bulldog-2-300x200.jpg',
                'categoryId' => '1',
                'price' => 230,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Alaskan Malamute Puppies For Adoption',
                'description' => 'The Alaskan Malamute is the largest of the Arctic dogs. This thick, well-built dog is solid with a plumed tail that is held over the back.',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2015/07/alaskan-malamute-pup.jpg',
                'categoryId' => '1',
                'price' => 188,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Jack Russell Terrier Puppies For Adoption',
                'description' => 'The Jack Russell Terrier is sturdy, hardy, and robust in appearance. They are outgoing with a keen expression. They have an inquisitive nature. This compact breed is very vocal but is never “yappy”.',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2013/10/Jack-Russell-Terrier-Puppies.jpg',
                'categoryId' => '1',
                'price' => 258,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Missy',
                'description' => 'Why hello there!My name is Missy,Everyone always says how pretty I am, but I\'m smart too! I\'m playful, cheeky, and I even know how to play fetch - what more could you want?!After a good long walk and play in the garden I love nothing more than curling up somewhere warm and cosy.I have my paws crossed to hear from you, Missy xx',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/185134/462301.jpg?itok=CPdLD-Wc',
                'categoryId' => '1',
                'price' => 300,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Nanook',
                'description' => 'I am an energetic boy, who loves playing fetch or a game of tug of war. I love my walks and I am typical of my breed, so can only be let off lead in secure areas. I enjoy company and having attention, so I would really love a new home where my humans are around more to entertain me.   ',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/446745.jpg?itok=THXnhKYb',
                'categoryId' => '1',
                'price' => 238,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Sandy',
                'description' => 'Sandy is a shy and quiet dog that takes time to get used to new environments and being around unfamiliar people.Sandy is looking for a calm and quiet home with understanding and patient owners, who will let Sandy take the time she needs to settle in at a slower pace.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/461364.jpg?itok=XImP_Nw2',
                'categoryId' => '1',
                'price' => 410,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Merlin',
                'description' => 'This little lad is a friendly sociable little chap who enjoys fuss and attention. He settles well in a home environment, and will hop up on a comfy chair for a nap!',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/445091.jpg?itok=rhirKz00',
                'categoryId' => '1',
                'price' => 338,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Reggie',
                'description' => 'We will need some help with housetraining as we were unable to go outside when we needed to and also nee to improve some basic commands. We really would love to find a new home together as we have always been the best of friends and we would be very sad to be apart, so if you feel you could offer us both a lovely new home, please fill in a Homefinder, we look forward to meeting you.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/460211.jpg?itok=NU3q5x4o',
                'categoryId' => '1',
                'price' => 337,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Barkley',
                'description' => 'This beautiful boy is Barkley! He is an exuberant 9 month old Springer Spaniel X Border Collie.Barkley loves to chase tennis balls, going for walkies and playing with other dogs.Due to his exuberance, Barkley could potentially live with older children and a dog that could cope with his energy levels, providing they all get along here at the centre first.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/1105634/461270.jpg?itok=DBqdcGwi',
                'categoryId' => '1',
                'price' => 278,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Billy',
                'description' => 'Billy is a wonderful older chap, with bundles of character. Despite being blind, he has a fantastic zest for life and loves to go on walks and discover all the sniffs of the Hertfordshire countryside.After a nice walk, Billy loves nothing more than having a snuggle and curling up with you for a fuss.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/1104115/458748.jpg?itok=M2-xoPFk',
                'categoryId' => '1',
                'price' => 321,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'NooNoo',
                'description' => 'I came to the Blue Cross as a stray where I have been given a warm place to stay and food to eat. But apparently life gets even better than this, so I\'ve been told.I\'m a lovely older girl with a lot of love to give, I\'m not typical of my breed and love to have a fuss and be friends with everyone.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/1105808/461958.jpg?itok=c4tGCBea',
                'categoryId' => '1',
                'price' => 317,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Rosie',
                'description' => 'A quiet retirement home with a nice garden to potter about inShe may be able to live with other petsRosie is diabetic so owners with experience of this would be perfect however it’s very easy to learnA nice cosy bed or lap to snuggle up on and lots and lots of cuddlesRosie can live with older children but doesn’t mind occasional visits from little onesIf you can offer Rosie the peaceful home she is looking for, please fill in a home finder today.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/1104183/465187.jpg?itok=wGvHY3Lo',
                'categoryId' => '1',
                'price' => 345,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Toby',
                'description' => 'As you can see from Toby’s photos he is a very cute boy. Toby just adores attention, fuss and cuddles on the sofa with you. He enjoys lots of walks and playtime. Toby will need a bit more time spent on him with training.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/466006.jpg?itok=s5palZpO',
                'categoryId' => '1',
                'price' => 300,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Zara',
                'description' => 'Hello!!! My name is Zara I’m a beautiful lurcher cross Saluki, I’m looking for: • A home with children pending meets •	Only dog in the home. •	Can live with dog savvy confident cats. •	Needs a very active home. •	Rural area. If you think you’re the right home for Zara please fill in a home finder today!',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/465856.jpg?itok=o4d91ceU',
                'categoryId' => '1',
                'price' => 258,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Maddie',
                'description' => 'Meet Maddie,Maddie is a very loving dog and full of character. You might have been able to guess from her pictures she is what we would call a mongrel! But a very unique one we think, wouldn’t you agree?She loves the company of people, and is very tactile, loving a good scratch. She enjoys a cuddle on the sofa and a good afternoon snooze.If you think Maddie could fit into your heart and home, please fill out a form online or pop into the centre and have a chat with a member of the team.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/1102750/467107.jpg?itok=lxd64BAg',
                'categoryId' => '1',
                'price' => 299,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Seal Point Persian kitten 3 weeks old',
                'description' => 'New! Elite Persian kitten from Europe. In excellent breed type. male, 2.5 month old. Litter box trained. Can deliver to other states and worldwide . For video and parents pictures please call 347-387-1796 or Email Email Me Here. We provide 180 days warranty on all our kittens and puppies!!! Please check our web site: www.catsdogs.us for complete listing.',
                'images' => 'http://www.elifehow.com/uploads/images/2017/10/1508309541722TW4.jpg',
                'categoryId' => '2',
                'price' => 156,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Red Shaded Male Scottish Straight',
                'description' => 'This beautiful kitten is available for reservation. The best time for a kitten to go to a new loving home is around 3 months old after the kitten gets its second shot and deworming so his immune system is strong enough to adjust to a new environment. Our kittens are born in New York and been raised in a loving home atmosphere ensuring they get enough of attention and care. Kittens are litter trained. They are very affectionate and playful!!! Love people and kids! We commit to healthy and quality reproduction as well as outstanding customer service and experience. We offer 1 year warranty for genetic health problems. Parents are TICA registered. Registration for a kitten is additional $300. To reserve a kitten we accept $400 nonrefundable deposit via PayPal or Venmo. You are welcome to visit our cattery or FaceTime to see the kitten. Shipping to another state is available. We ship our kittens with a nanny in the cabin so its less stress for kitten and its additional $400. We don not recommend to ship kittens by Cargo, its only $100 difference. Enjoy your kitten!',
                'images' => 'https://static.tildacdn.com/tild3064-3335-4563-a233-343761393664/Photo_Apr_11_8_13_28.jpg',
                'categoryId' => '2',
                'price' => 113,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'New! Elite Persian kitten from Europe',
                'description' => 'New! Elite Persian kitten from Europe. In excellent breed type. male, 2 month old. Litter box trained. Can deliver to other states and worldwide . For video and parents pictures please call 347-387-1796 or Email Email Me Here.',
                'images' => 'https://kenh14cdn.com/2018/5/21/photo-13-1526915711548979409596.jpg',
                'categoryId' => '2',
                'price' => 141,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Female White Persian kitten',
                'description' => 'Born July 18th. Take home day after September 18th, with shots, deworming and health certificate. Parents are CFA registered FIV/ FELV- negative no PKD illness in their generation. Breeding rights are extra.',
                'images' => 'https://tinnhanh.dkn.tv/wp-content/uploads/2018/04/la-meo-thi-phai-bat-chuot-anh-0.jpg',
                'categoryId' => '2',
                'price' => 365,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Male White Persian Kitten',
                'description' => 'Born on July 18th and will be ready to take home the day after September 18th with shots, deworming and health certificates. Parents are CFA registered.',
                'images' => 'https://baomoi-photo-1-td.zadn.vn/w700_r1/18/04/14/139/25661852/8_106289.jpg',
                'categoryId' => '2',
                'price' => 221,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'blue cream female persian kitten reserved',
                'description' => 'Born July 18th and will be ready to take home the day after September 18th with shots, deworming and health certificate. Parents are CFA registered, FIV / FELV -negative no PKD illness in their generation. Breeding rights are extra.',
                'images' => 'https://baomoi-photo-1-td.zadn.vn/w700_r1/18/04/14/139/25661852/5_123355.jpg',
                'categoryId' => '2',
                'price' => 111,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Cat',
                'description' => 'Ugly fluffy dogs',
                'images' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVTttxDHEya3gQuiHCz1avTmyDc_mChorNQCD2iYwbQGsdxU4c',
                'categoryId' => '2',
                'price' => 115,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'A gorgeous blue cream
',
                'description' => 'molly is looking for her forever home...she is 11wks.. comes vet ck,wormed1st shot papers $500 Blue cream & white dilute tortoiseshell persian.',
                'images' => 'https://kenh14cdn.com/2017/taken-byhana-kitty-13-png-700-1491293405359.jpg',
                'categoryId' => '2',
                'price' => 199,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Gorgeous boy Persian red and white kitten',
                'description' => 'Wonderful, sweet personality, loves to play and purrs a lot!!!',
                'images' => 'https://cdn.pose.com.vn/legacy/images/baiviet/201609/scrape_14734787761731_m6-1473395779251.jpg',
                'categoryId' => '2',
                'price' => 134,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Cfa chocolate point male persian himalayan kitten',
                'description' => 'CFA Chocolate Point Male Persian Himalayan Kitten',
                'images' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQX_pMcjp4iEKdSdi_lTbWyHctczLj7KQtw9QJ6t-f2sladfZbLHA',
                'categoryId' => '2',
                'price' => 123,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Budge',
                'description' => 'Where do I start? I am a very sweet little boy. I have come from a home where unfortunately their circumstances changed and they couldn\'t take care of me anymore. I take a while to get to know people but once I come out of my shell I am very friendly. I do like a fuss every now again but I mostly just like to chill and sleep.I am quite nervous of new things so I don\'t really tend to go out side much, the big wide world is just a bit too big for me.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/242684/462276.jpg?itok=ePeRlUSB',
                'categoryId' => '2',
                'price' => 134,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Spud',
                'description' => 'I like to perch on the end of the sofa and I love to play with my toys. I also love my food! I know exactly when my meals time are!I have been enjoying having a home to myself, but I could potentially live with another quiet cat like myself with slow introductions.I have never been outside before so I’m not street smart, this just means I will need to be rehomed as an indoor cat or away from busy roads.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/376347.jpg?itok=cmP07reK',
                'categoryId' => '2',
                'price' => 139,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'title' => ' Lola',
                'description' => 'I\'m a beautiful tortie girl with a winning personality. I just love people and am so affectionate with everyone I meet. I\'m currently spending time at a foster carer\'s who has given me a glowing report; I really am a good girl!I like to play at times and will come and sit in your lap for attention. If you\'d like to know a bit more about me or find out if we\'d be a suitable match- fill out a homefinder today!',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/411340.jpg?itok=btqDszMt',
                'categoryId' => '2',
                'price' => 153,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'title' => 'Beatrix',
                'description' => 'I was found along with my two siblings in a wall cavity covered in dust with no mum. The team here have been hand rearing me but now I am old enough to start looking for my new home. I am very playful energetic and love falling asleep in strange positions. I can be a little enthusiastic at times during play as haven\'t had a mum how to teach me. Because of this I could live with children pending a meet but will need to be older children.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/462429.jpg?itok=bVBzti9H',
                'categoryId' => '2',
                'price' => 133,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'title' => 'Ollie',
                'description' => 'I am a little shy and may take a bit of time getting to know you, but once I do, I love a good fuss! I am also very inquisitive and like to explore around my pen!If you’ve got room in your heart for Ollie, then please fill in an application.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/2106082/463342.jpg?itok=FUMXowCE',
                'categoryId' => '2',
                'price' => 167,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'title' => 'Winnie',
                'description' => 'Harry and Winnie are sensitive souls and are looking for a quieter home, with people who are happy to give them time and space to settle in.One they are comfortable, they\'re both super sweet and no trouble at all.Harry and Winnie can live with older children. They\'ve never lived with dogs, but we\'d be happy to discuss with anyone who has dogs to see if they\'d be a right match!',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/446648.jpg?itok=FG1b7h_b',
                'categoryId' => '2',
                'price' => 145,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'title' => 'Libby',
                'description' => 'I\'ve been here at the cattery in Grimsby for over 40 days now, during this time I have not one person interested in me. I just don\'t understand I hear the staff saying that I\'m every so pretty I know I\'m friendly.My previous owner loved me very much but unfortunately she had to move and the landlord wasn\'t to happy with me staying.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/2105072/461646.jpg?itok=Z5jGQUqs',
                'categoryId' => '2',
                'price' => 188,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'title' => 'Buffy',
                'description' => 'I’m gentle and sweet when I know you, and do like a little fuss and occasionally a nice warm lap to perch on. I’m quite happy pottering about the home and garden doing my own thing if you’re busy though! As long as there’s plenty of sun to bask in, and comfy spots to snooze the day away, I think I’ll be very content indeed!',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/2103474/451218.jpg?itok=VjnrbOqH',
                'categoryId' => '2',
                'price' => 113,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'title' => 'Mr Tom',
                'description' => 'I am a confident chap who loves to be the centre of attention. I like strokes and really enjoy a good brush. I\'m playful as well. I\'m the whole package, to be honest!I have been told once I am settled in my new home I can start to go outside which I am very excited about! I wouldn\'t mind if you are out at work during the day as long as I have access to the outdoors so I can come and go when I want.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/465804.jpg?itok=M3JkNk_3',
                'categoryId' => '2',
                'price' => 188,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'title' => 'Peat',
                'description' => 'I was found as a stray with my mum and siblings. I will take a bit of time to get use to living in a home and being around people. So far I really like being stroked, and love my toys.Due to my age I am looking for someone who is around a lot during the day.',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/465479.jpg?itok=c3cj_boJ',
                'categoryId' => '2',
                'price' => 135,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'title' => 'Norman',
                'description' => 'Hey there – my name is Norman and as you can see from my photo’s I’m a very handsome and laid back kitty! I am looking for a new home to call my own and if you like the look of me, please read on. I absolutely love attention and am happy being stroked. I like to sleep all day and party all night (outside) but always come back in the morning for my breakfast and human fusses! I can get over excited a bit after too much fuss and have been known to play nip so would be better with older children - but I am a loving and wonderful kitty! I really do like lots of attention so would like to be the only pet in the house so I can have it all! I think I should be very popular so you better hurry if you are interested, register today! Love Norman X',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/466582.jpg?itok=BSjZTG1V',
                'categoryId' => '2',
                'price' => 139,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'title' => 'Leila',
                'description' => 'I enjoy snoozing and will sometimes seek a cuddle and fuss from you on your lap but I do enjoy finding somewhere cosy to snuggle up in and have some alone time. I\'d really love some toys in my new home as well as I find these really exciting and enjoy play with my current family on a daily basis. I love the outdoors, I often supplement my diet with the odd snack!',
                'images' => 'https://www.bluecross.org.uk/sites/default/files/styles/thumbnail_pet/public/pets/2104954/449403.jpg?itok=2xtHE9f4',
                'categoryId' => '2',
                'price' => 146,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Mad About Dog Bark Stop Collar',
                'description' => 'Mad about dog presents pet collar charm. It is made from plastic material and is suitable for dog’s . It is black with white in colour, has plain design and has a shape.',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2017/01/814RLwHXgYL._SL1500_.jpg',
                'categoryId' => '3',
                'price' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Doggy Dolly Doggydolly Shirt For Dogs',
                'description' => 'Doggy dolly presents pet apparels and accessories. It is suitable for dog’s. It is made from cotton material and is multi-coloured in colour. It has a . This item contains shirt',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2017/02/91W4qnSE0SL._SL1500_.jpg',
                'categoryId' => '3',
                'price' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Mad About Dog Cotton Shoes ',
                'description' => 'This shoes for dogs from the house of Mad About Dog is made of cotton material. It comes in pink color. This shoes gives utmost comfort for your pets and it can be hand washed',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2017/01/71T8TWLqjL._SL1500_.jpg',
                'categoryId' => '3',
                'price' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Mad About Dog Fancy Clip',
                'description' => 'Mad about dog presents pet collar charm. It is made from net material and is suitable for dog’s . It is black in colour, has plain design and has a round shape.',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2017/02/913MOgI1hKL._SL1500_.jpg',
                'categoryId' => '3',
                'price' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Mad About Dog Fancy Butterfly Dress',
                'description' => 'Mad about dog presents pet apparels and accessories. It is suitable for dog’s. It is made from chiffon material and is pink in colour. It has a plain. This item contains one dress.',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2017/01/A10C0UUc6VL._SL1500_.jpg',
                'categoryId' => '3',
                'price' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Mad About Dog Fancy Clip, 16 Cm X 16 Cm',
                'description' => 'Mad about dog presents pet collar charm. It is made from net material and is suitable for dog’s . It is black in colour, has plain design and has a round shape.',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2017/02/91FsX47tZUL._SL1500_-1.jpg',
                'categoryId' => '3',
                'price' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Mad About Dog Fancy Collar 1',
                'description' => 'Mad about dog presents pet collar charm. It is made from polyester material and is suitable for dog’s . It is pink in colour, has embellished design and has a rectangle shape.',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2017/01/81YcufC1jUL._SL1500_.jpg',
                'categoryId' => '3',
                'price' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Mad About Dog Fancy Collar 2',
                'description' => 'Mad about dog presents pet collar charm. It is made from stone material and is suitable for dog’s . It is transparent in colour, has embellished design and has a rectangle shape.',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2017/01/81qZaUg5jIL._SL1500_.jpg',
                'categoryId' => '3',
                'price' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Mad About Dog Fancy Hats 1',
                'description' => 'Mad about dog presents pet apparels and accessories. It is suitable for dog’s. It is made from velvet material and is red in colour. It has a plain. This item contains one piece hat',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2017/01/91ebS3m3dwL._SL1500_.jpg',
                'categoryId' => '3',
                'price' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Mad About Dog Fancy Hats 2',
                'description' => 'Mad about dog presents pet apparels and accessories. It is suitable for dog’s. It is made from net material and is navy blue in colour. It has a plain. This item contains one piece hat.',
                'images' => 'http://www.dogbazar.org/wp-content/uploads/2017/01/A13hrYeJanL._SL1500_.jpg',
                'categoryId' => '3',
                'price' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


            [
                'title' => 'Cat for cat TT',
                'description' => 'HAPPY TOGETHER FOR LIVING ROOMS - RAISING TO COLLECTING ANIMALS',
                'images' => 'http://petstore.com.vn/379-814-large/chuot-bong-cho-meo-tt.jpg',
                'categoryId' => '3',
                'price' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Gauntlet cat with TT bulb',
                'description' => 'Colorful jute cat toy with cage balloons inside - with cylindrical roller design that makes the cats even more exciting.',
                'images' => 'http://petstore.com.vn/318-597-large/do-choi-meo-hinh-ong-kem-bong-tt.jpg',
                'categoryId' => '3',
                'price' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Cat scratches TT',
                'description' => 'Mini cat fish toy with colorful jute wrapped around to help the cat grind',
                'images' => 'http://petstore.com.vn/317-596-large/ca-meo-cao-tt.jpg',
                'categoryId' => '3',
                'price' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Cat\'n Mouse cat litter TT',
                'description' => 'Cat\'n Mouse toy is made of non-toxic plastic, on the face of the fabric is suitable for cat grinding. The product is specially designed with a rotary mouse motor inside to attract, stimulate cats, and training the mouse processing instincts in the cat family.',
                'images' => 'http://petstore.com.vn/313-586-large/bo-do-choi-meo-gan-chuot-quay-cat-mouse-tt.jpg',
                'categoryId' => '3',
                'price' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Dougez TT three-layer cat kit',
                'description' => 'Dougez\'s products are made from environmentally friendly high-grade PP, ensuring no toxicity. Three-tiered cat toy set with 3 plastic balls attached, can help the owner to set the number of balls in the floor. Anti-skid anti-slippering helps keep your cat safe from catastrophic raids - it\'s a must-have item to help your cat cope with stress, less loneliness at home alone.',
                'images' => 'http://petstore.com.vn/312-582-large/bo-do-choi-meo-3-tang-dougez-tt.jpg',
                'categoryId' => '3',
                'price' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Antique bells for dogs',
                'description' => 'Dog bells for dogs or cats for many models',
                'images' => 'http://petstore.com.vn/51-127-large/chuong-co-cho-cho-nhieu-mau.jpg',
                'categoryId' => '3',
                'price' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Mouse for cat TT',
                'description' => 'Mouse-shaped toys made of multicolored fabric, used as toys for cats',
                'images' => 'http://petstore.com.vn/216-357-large/chuot-dan-cho-meo-tt.jpg',
                'categoryId' => '3',
                'price' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'CAT CAT FISH CAT',
                'description' => 'Mouse-shaped toys made of multicolored fabric, used as toys for cats',
                'images' => 'http://petstore.com.vn/215-356-large/can-cau-meo-fat-cat-tt.jpg',
                'categoryId' => '3',
                'price' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Cat scratches',
                'description' => 'Cats\' nail grippers - using natural jute material that surrounds the wood, are essential to avoid scratching the inside of your home such as couches, car seats, etc.',
                'images' => 'http://petstore.com.vn/212-408-large/ban-meo-cao.jpg',
                'categoryId' => '3',
                'price' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Spring-loaded felt felt',
                'description' => 'A cat-and-mouse toy with a dummy mouse is attached to the sole by a hard rubber spring that covers the outside of the environment, swings back and forth repeatedly to attract attention and stimulate the mat. the power of cats.',
                'images' => 'http://petstore.com.vn/211-407-large/chuot-lo-xo-bc-ni.jpg',
                'categoryId' => '3',
                'price' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'flexi Neon Dog Lead',
                'description' => 'Modern and safe: a retractable lead in black casing with a yellow print pattern. The 5m lead is bright neon yellow. Stay visible when the light starts to fades.',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/flexi/neon/dog/lead/8/400/flexi_22_8.jpg',
                'categoryId' => '3',
                'price' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Dog Lead flexi Giant XL',
                'description' => 'This compact, high-viz lead is designed for large, strong dogs (+50kg). The retractable lead stretches to 8m and has a robust casing, a comfortable soft grip and easy to use controls.',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/dog/lead/flexi/giant/xl/m/3/400/69555_hundeleine_flexi_xl_8_m_neon_top_seller_3.jpg',
                'categoryId' => '3',
                'price' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Trixie Dog Jacket Tcoat Orléans',
                'description' => 'Water-repelling dog coat with an extra soft fleece lining. The reflecting seams provide more safety in the dark. Colour: black. ',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/trixie/dog/jacket/tcoat/orlans/1/400/51717_trixie_hundemantel_or_1.jpg',
                'categoryId' => '3',
                'price' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Dog Beach T-Shirt',
                'description' => 'A cool fashion t-shirt for dogs, made from light, breathable mesh material. It has a bright flower design to mimic a Hawaiian shirt and a beach slogan, with elastic and Velcro to ensure a great fit. ',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/dog/beach/tshirt/4/400/79371_hundeshirt_beach_fg__4.jpg',
                'categoryId' => '3',
                'price' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'FURminator Short Hair L',
                'description' => 'FURminator Short Hair L for large dogs between 23 and 40 kg with a coat shorter than 5 cm, for a glossy coat and less hair in your home, reduces shedding by up to 90%, with hair removal function. ',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/furminator/short/hair/l/4/400/48928_PLA_FURminator_Kurzhaar_L_253770_112532_furminator_kurzhaar_L_012013__4.jpg',
                'categoryId' => '3',
                'price' => 33,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Pet Head Shampoo Puppy Fun',
                'description' => 'Hypoallergenic, pH-neutral dog shampoo with extra gentle formula and delicious orange scent. With safflower oil and shea butter for a soft, supple coat. Also ideal for puppies',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/pet/head/shampoo/puppy/fun/1/400/57231_pet_head_welpen_shampoo_puppy_fun_hs_05_2015_1.jpg',
                'categoryId' => '3',
                'price' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'KONG Massage Brush Zoom Groom',
                'description' => 'Special dog-shaped massage brush for dogs from KONG, for blissful fur care and gentle affection .',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/kong/massage/brush/zoom/groom/2/400/26796_PLA_Kong_Dog_Massagebuerste_Zoom_Groom_HS_ZG1_ZoomGroom_Boysenberry_2.jpg',
                'categoryId' => '3',
                'price' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'KONG Winders Fox',
                'description' => 'Cute dog toy with a tightly coiled rope body, fleecy fur and stretchy tails at one end to encourage play. Featuring a robust design, minimal stuffing and a squeaker inside for even more fun. ',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/kong/winders/fox/3/400/485431_winders_fox_3.jpg',
                'categoryId' => '3',
                'price' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'KONG Ball',
                'description' => 'Especially robust ball made of natural rubber. This bright red ball from KONG is very durable and has a very high bounce, ideal for throwing, retrieving and chewing. Can also be filled with treats. ',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/kong/ball/1/400/74322_pla_kong_snack_ballloch_1.jpg',
                'categoryId' => '3',
                'price' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'KONG Gyro',
                'description' => 'Dynamic dog toy that keeps your pet guessing! It can roll and tip in any direction that your dog won’t be able to predict, and can be filled with tasty treats or dry food to keep your dog’s attention! ',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/kong/gyro/0/400/74248_pla_kong_gyro_s_0.jpg',
                'categoryId' => '3',
                'price' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Weruva Classics Mideast Feast with Grilled Tilapia in Gravy Wet Cat Food',
                'description' => 'Weruva Classics natural cat food, made with the highest quality cuts of meat or lean fish loins provide high protein and low fat recipes. All meat is hand flaked right off the bone and hand packed for optimal quality.',
                'images' => 'https://petco.scene7.com/is/image/PETCO/2892436-center-1?$PLP-category$',
                'categoryId' => '4',
                'price' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'title' => 'Weruva Classics Paw Lickin\' Chicken Chicken Recipe in Gravy Wet Cat Food',
                'description' => 'Weruva Classics natural cat food, made with the highest quality cuts of meat or lean fish loins provide high protein and low fat recipes. All meat is hand flaked right off the bone and hand packed for optimal quality.',
                'images' => 'https://petco.scene7.com/is/image/PETCO/2892532-center-1?$ProductDetail-large$',
                'categoryId' => '4',
                'price' => 19,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Soulistic Aqua Grill Tilapia & Tuna Dinner Adult Canned Cat Food in Gravy',
                'description' => 'Your cat will love the wholesome, tasty meats and juices in Soulistic Adult Canned Cat Food in Gravy, available exclusively from Petco.',
                'images' => 'https://s7d1.scene7.com/is/image/PETCO/1229117-center-1?$ProductDetail-large$',
                'categoryId' => '4',
                'price' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Fancy Feast Seafood Gourmet Cat Food Variety Pack',
                'description' => 'Fancy Feast Gourmet Cat Food Variety Pack',
                'images' => 'https://petco.scene7.com/is/image/PETCO/840505-center-1?$ProductDetail-large$',
                'categoryId' => '4',
                'price' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Fancy Feast Broths Creamy Collection Cat Food Complement, Case of 12, 1.4 oz.',
                'description' => 'Fancy Feast Broths Creamy Collection Cat Food Complement, Case of 12, 1.4 oz.',
                'images' => 'https://s7d1.scene7.com/is/image/PETCO/2411882-center-1?$ProductDetail-large$',
                'categoryId' => '4',
                'price' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Fancy Feast Purely Skipjack Tuna Adult Cat Food Trays, 2 oz., Case of 10',
                'description' => 'Fancy Feast Purely Adult Cat Food Trays are real, natural seafood, poultry or beef plus vitamins & minerals, in a delicate broth crafted without by-products or fillers. A fresh taste your cat truly desires.',
                'images' => 'https://petco.scene7.com/is/image/PETCO/2464554-center-1?$ProductDetail-large$',
                'categoryId' => '4',
                'price' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Fancy Feast Broths Creamy Tuna, Chicken & Whitefish Cat Food Complement',
                'description' => 'Feed your feline family member Fancy Feast Broths Classic Cat Food Complements. These gourmet broths feature real meat in a decadent, silky broth. Choose from delectable flavors including tuna, salmon, mackerel and more. The savory, delicate broth is filled with tender morsels of real meat that your cat is sure to love. No by-products or fillers are included. Each wet cat food pouch is easy to open and provides a tasty way to add texture to your cat s daily meals. Serve these Fancy Feast cat food complements in addition to your cat s regular food.',
                'images' => 'https://s7d1.scene7.com/is/image/PETCO/2411874-center-1?$ProductDetail-large$',
                'categoryId' => '4',
                'price' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Fancy Feast Broths Classic Collection Cat Food Complement',
                'description' => 'Fancy Feast Broths Classic Collection Cat Food Complement, Case of 12, 1.4 oz.Savory wet cat food recipes featuring flavorful broth',
                'images' => 'https://s7d1.scene7.com/is/image/PETCO/2411891-center-1?$ProductDetail-large$  ',
                'categoryId' => '4',
                'price' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Fancy Feast Broths Classic Tuna, Shrimp & Whitefish Cat Food ',
                'description' => 'Fancy Feast Broths Classic Tuna, Shrimp & Whitefish Cat Food Complement, 1.4 oz.',
                'images' => 'https://s7d1.scene7.com/is/image/PETCO/2278815-center-1?$ProductDetail-large$',
                'categoryId' => '4',
                'price' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Royal Canin Feline Health Nutrition Kitten Instinctive Thin Slices In Gravy Wet Cat Food',
                'description' => 'Feline Health Nutrition wet canned formulas are designed around a cat\'s nutritional needs and instinctive preferences. Our formulas were created with the optimal balance between proteins,',
                'images' => 'https://petco.scene7.com/is/image/PETCO/2416878-left-1?$ProductDetail-large$',
                'categoryId' => '4',
                'price' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Applaws Mixed Selection Packs',
                'description' => 'Three different varieties of delicious, 100% natural supplementary dog food for adult dogs. Applaws high quality dog food contains no artificial additives or animal by-products.',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/applaws/mixed/selection/packs/6/400/67986_pla_applaws_recipe_se_6.jpg',
                'categoryId' => '4',
                'price' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Applaws Dog Food in Broth',
                'description' => 'Applaws canned dog food is a premium natural dog food in tasty varieties without gluten, or artificial colours, flavours, or preservatives.',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/applaws/dog/food/in/broth/x/g/2/800/22651_PLA_Applaws_Hundefutter_Huhn_156g_2.jpg    ',
                'categoryId' => '4',
                'price' => 19,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'James Wellbeloved Senior Pouches – Turkey with Rice',
                'description' => 'Complete balanced wet food with hypoallergenic ingredients, including turkey as a single source of protein and natural goodness. It contains valuable vitamins and minerals',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/james/wellbeloved/senior/pouches/turkey/with/rice/5/400/78434_pla_crownpetfoods_jameswellbelovedpouches_turkey_10x150g_5.jpg',
                'categoryId' => '4',
                'price' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Wolf of Wilderness',
                'description' => 'Species appropriate wet dog food with only a single source of animal protein, enriched with fruits of the forest and wild herbs. This grain-free dog food is based on the wolf\'s natural eating habits.',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/wolf/of/wilderness/x/g/7/400/wow_classic_oakwoods_400g_1000x1000_7.jpg',
                'categoryId' => '4',
                'price' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Forthglade Complete Meal Adult Dog - Multipack',
                'description' => '3  different delicious flavours of Forthglade wet dog food for adult dogs aged 1-7, all made with brown rice with added glucosamine and chondroitin. Free from gluten, soya, egg and dairy products.',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/forthglade/complete/meal/adult/dog/multipack/4/400/68594_pla_forthglade_adult_multicase_brownrice_4.jpg',
                'categoryId' => '4',
                'price' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Animonda GranCarno Original Junior',
                'description' => 'Complete feed for puppies and young dogs. Highly meaty, no grain, soy or artificial additives, rich in vitamins & minerals. Gently cooked to preserve nutrients.',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/animonda/grancarno/original/junior/x/g/2/400/51196_pla_animonda_grancarn_2.jpg',
                'categoryId' => '4',
                'price' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Cosma Gourmet Box Mixed Pack ',
                'description' => 'Treat your cat while stocks last with this tasty Cosma Gourmet Box Mixed Pack - with 14 cans of Cosma in Jelly 85g mixed pack in a cute gift box! .',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/cosma/gourmet/box/mixed/pack/x/g/3/400/325409_edycja_specjalna_pude_ko_cosma_14_x_85_g_09_13_copy_3.jpg',
                'categoryId' => '4',
                'price' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Felix As Good As It Looks in Jelly',
                'description' => '24 pouches of Felix "As Good As It Looks" in the value multi-pack with 4 x 6 different delicious varieties, cat food full of tender, chunky pieces of meat in a tasty jelly.',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/felix/as/good/as/it/looks/in/jelly/x/g/1/400/190878_24_1000x1000_1.jpg',
                'categoryId' => '4',
                'price' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Royal Canin Veterinary Diet – Renal with Tuna',
                'description' => 'A complete wet cat food for cats over 6 months old suffering from renal insufficiency or hepatic encephalopathy. It can also reduce the risk of kidney and bladder stones, for better renal health.',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/royal/canin/veterinary/diet/renal/with/tuna/8/400/471676_royal_canin_veterinary_diet_renal_mit_thunfisch_01_8.jpg',
                'categoryId' => '4',
                'price' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Royal Canin Veterinary Diet - Renal Chicken',
                'description' => 'Complete dietetic canned wet food for cats with chronic renal disease (CKD), it is well accepted and can help prevention of urinary stones and to support renal function. With alkalinising agents.',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/royal/canin/veterinary/diet/renal/chicken/8/400/67399_pla_royal_canin_vet_renal_chicken_dose_8.jpg',
                'categoryId' => '4',
                'price' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Whiskas Casserole Selection in Jelly',
                'description' => 'Now when you buy 12 x 85g Whiskas Casserole Selections in Jelly, you\'ll only pay for 10 - that\'s 2 pouches free!',
                'images' => 'https://shop-cdn-m.shpp.ext.zooplus.io/bilder/x/g/whiskas/casserole/selection/in/jelly///free/4/400/610137_4.jpg',
                'categoryId' => '4',
                'price' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
